services:
  db:
    image: groonga/pgroonga:latest-alpine-17
    container_name: tgdrive_${DRIVE_NAME}_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - /opt/tgdrive/${DRIVE_NAME}/postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: ghcr.io/tgdrive/teldrive:1.6.19
    container_name: tgdrive_${DRIVE_NAME}
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - /opt/tgdrive/${DRIVE_NAME}/config.toml:/config.toml
      - /opt/tgdrive/${DRIVE_NAME}/storage.db:/storage.db
    ports:
      - "${APP_PORT}:8080"
